- name: deploy to tomcat
  hosts: web
  become: yes
  tasks:
    - name: copy from src to dest
      copy:
        src: "/var/snap/jenkins/4870/workspace/tomcatmvn_ansi/target/MavenAnsiWebApp.war"
        dest: "opt/tomcat/webapps/MavenAnsiWebApp.war"
        remote_src: no
        
    - name: restart tomcat
      systemd: 
        name: tomcat
        state: restarted
    
