- name: Deploy in Tomcat
  hosts: web
  become: yes
  tasks:
    - name: Copy WAR to Tomcat
      copy:
        src: "/var/snap/jenkins/4870/workspace/tomcatmvn_ansi/target/MavenAnsiWebApp.war"
        dest: "/opt/tomcat/webapps/MavenAnsiWebApp.war"
        remote_src: no

    - name: Restart Tomcat
      systemd:
        name: tomcat
        state: restarted
